### ISSUE TITLE
Hacer más legible la agenda

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/kitcat#26]
- [x] Las celdas que ahora están en #30cc94 pasarlas a #ffffff
- [x] Links en #30cc99
- [x] Columna de hora con fondo en #ffffff
- [x] Hover en #30cc99
- [x] Columnas al 15% (hora) 85% (Actividad)

**Comment by diegobeauroyre** [comment]
![screen shot 2015-01-20 at 7 01 19 pm](https://cloud.githubusercontent.com/assets/6226604/5829406/60486c0a-a0d7-11e4-9582-17bab3348bfb.png)

**Comment by poguez** [comment]
al hover de qué elemento te refieres @diegobeauroyre ?

**Comment by diegobeauroyre** [comment]
Al de la hora, no pude ponerlo ahí pero el de las 10:00

**Comment by poguez** [comment]
![screen shot 2015-01-21 at 12 36 45 pm](https://cloud.githubusercontent.com/assets/732015/5842420/417422cc-a16a-11e4-9309-ceec9be50812.png)

**Comment by juanpabloe** [comment]
cómo la ves ahora @diegobeauroyre ?

**Comment by juanpabloe** [comment]
listo con #31
